### ISSUE TITLE
If VASP does not even start running custodian doesn't raise error

### ISSUE THREAD

**Issue by albalu** [materialsproject/custodian#37] opened 2016-12-15 00:14 UTC
When reporting bugs/issues, please supply the following information. If this 
is a feature request, please simply state the requested feature.

## System

* Custodian version: 1.0.3 (master)
* Python version: 2.7.12

## Summary

* Custodian doesn't raise error if VASP doesn't even run for any reason. 
** example of importance: when files like OUTCAR are copied from the previous step, even if this step doesn't run, from OUTCAR and vasprun.xml, it looks like the job is already finished!
* The problem might be in Custodian._run_job() method: after "p = job.run()" custodian just assumes that VASP started running while it might not even start due to an error like this.

## Error message
 (this example is on NERSC in std_err.txt):
```
srun: error: slurm_receive_msg: Socket timed out on send/recv operation
srun: error: Unable to confirm allocation for job 3178405: Socket timed out on send/recv operation
srun: Check SLURM_JOB_ID environment variable for expired or invalid job.
```
but this may happen due to various reasons regardless of what this error message says.

## Suggested solution (if known)

I don't exactly know how VASP exits when it can't even start but the machine itself raises various errors like the one copied here. A check for this may be added before p = job.run()

**Comment by xhqu1981** [comment] 2016-12-15 00:26
It is not necessarily an issue of running a job but can be a consequence of incomplete killing a job by SLURM environment. I have ever experience some issues with SLURM. After a srun job is killed, the resource is not revoked and as a result, now job can't be submitted.

@albalu, To test, please set the terminate_func of Custodian to mpworks.workflows.wf_utils.ScancelJobStepTerminator. An example is available at Line 122~135 in mpworks.firetasks.custodian_task.

**Comment by xhqu1981** [comment] 2016-12-15 05:32
@albalu how long does the custodian job last in your example with the std_errr.txt?

**Comment by albalu** [comment] 2016-12-15 05:34
Is it recorded somewhere? I can't reproduce this error. If I restart the jobs run w/o problems but it looks like the VASP job did not even start as the vasp.out (the log file) is empty.

**Comment by xhqu1981** [comment] 2016-12-15 05:38
sacct -u <username> --format=JobID,JobName,MaxRSS,Elapsed

**Comment by xhqu1981** [comment] 2016-12-15 05:41
If some error happens in a VASP job, custodian killed it and try to fix it, in a SLURM environment, VASP can be stuck in the launching process. In such situation, vasp.out will be empty. If you see a long running time without any output in vasp.out, possibly it is the case.

**Comment by albalu** [comment] 2016-12-15 05:45
1. unfortunately, I can't tell how long the job was running based on this command as several vasp jobs run one after the other with one submission (i.e. under the same JobName)

2. I am certain that VASP did not start running as the files that are automatically generated right after VASP starts are not there including EIGENVAL, CONTCAR, etc.

I didn't quite understand how terminate_func works. My request is whether it is possible to stop Custodian from further running (e.g. validate vasprun.xml etc) and raise error in case such SLURM issues happen and vasp job doesn't even start!

**Comment by xhqu1981** [comment] 2016-12-15 05:47
If you can't see EIGENVAL, probably, VASP is stuck.

**Comment by xhqu1981** [comment] 2016-12-15 05:48
It makes custodian useless, because it will essentially never fix the failure although it is supposed to.

**Comment by xhqu1981** [comment] 2016-12-15 05:50
The solution I suggested is using an alternate way to kill VASP --- scancel. By using scancel, the subsequent VASP job (i.e. the error fixing step) can be launched successful.

**Comment by albalu** [comment] 2016-12-15 05:51
it doesn't mean that VASP is stuck it means that VASP never started running to begin with. As soon as VASP starts running a list of files including EIGENVAL, OSZICAR, CONTCAR, etc will be generated though some of them may be empty

**Comment by xhqu1981** [comment] 2016-12-15 05:52
If you just want to raise an error, I don't think it is necessary, because it just tells you the job is failed which you can always know.

**Comment by xhqu1981** [comment] 2016-12-15 05:53
If VASP is stucked in launching process, you won't be able to see EIGENVAL, OSZICAR. This error can be reproduced without custodian.

**Comment by xhqu1981** [comment] 2016-12-15 05:55
That is why I asked the question about the running time. If it finishes immediate, it can be said that VASP never run. But if the job lasts for one hour, it is quite accurate to say VASP is never run, right?

**Comment by xhqu1981** [comment] 2016-12-15 05:58
Or maybe we can check the issue in this way: is there any job finishes in <= 5 min? If VASP never kicked in, 5 min should be sufficient for the script to end.

**Comment by albalu** [comment] 2016-12-15 05:58
Yes I can tell by looking at it but if Custodian can't and that's why I submitted this issue. Let's say I copy OUTCAR and vasprun.xml from a successful self consistent step and I want to start a non-self consistent step through custodian. If the VASP job doesn't start after p = job.run() line, custodian will continue anyway and since VASP didn't start the OUTCAR and vasprun.xml are NOT empty (because we copied them from previous step) and they look just fine, so custodian treat this job as complete (e.g. validate vasprun.xml w/o problem) while it shouldn't because the VASP job didn't actually run.

**Comment by xhqu1981** [comment] 2016-12-15 06:00
Please look at my last comment, let's make sure that VASP indeed didn't run.

**Comment by albalu** [comment] 2016-12-15 06:03
there are vasp jobs that run fully in less than 10 seconds so that's not a good way. Not sure what's the best way to check this though.

**Comment by albalu** [comment] 2016-12-15 06:04
I didn't understand your last comment

**Comment by xhqu1981** [comment] 2016-12-15 06:07
You already answered it. You did have jobs finished within 5 mins. So, we can be sure that VASP never runs.  Now, I think a test case is the best way to start with.

**Comment by albalu** [comment] 2016-12-15 06:08
Could you please explain a case where VASP does run even after it's stuck for a long time but then the EIGENVAL file (though empty) is not generated?

**Comment by albalu** [comment] 2016-12-15 06:10
One idea is to check for the existence of ALL the following files 10 seconds after vasp is supposed to run:
EIGENVAL CHG CHGCAR CONTCAR DOSCAR OSZICAR OUTCAR PCDAT WAVECAR

**Comment by xhqu1981** [comment] 2016-12-15 06:13
For that issue, it is quite reproducible, whenever a custodian monitor finds an error in VASP output file, the fixing step VASP job will be always stuck, some file can produce but not all. However, it is on NERSC, several months ago. I don't think it is the case you are facing. Because in that case, the SLURM job takes a very long time to finished. The job is essentially stopped.

**Comment by xhqu1981** [comment] 2016-12-15 06:23
Are you able to access the NERSC ticket system? If so, please check ticket INC0087224. In that ticket, I and NERSC staff discuss and confirmed the issue.

**Comment by albalu** [comment] 2016-12-15 06:31
I think I failed to make myself understood. I am talking about a more general issue not a specific NERSC error. Consider the following scenario:

1. OUTCAR and vasprun.xml are copied from a **successful** vasp step to the current folder, or I am simply running the new step in the same folder.
2. Custodian attempts to run vasp
3. **for any reason**, vasp does not start running
4. custodian is monitoring vasprun.xml and OUTCAR and based on that it looks like the current job ran without errors
5. Custodian finishes without raising errors while it should have because the VASP did not even run.

I am 100% sure that this is what happened in my case. Is the problem clear?

**Comment by xhqu1981** [comment] 2016-12-15 06:46
Got it. Now we understand that you "OUTCAR and vasprun.xml are copied from" other folders. I am not sure custodian are designed to handler such situation. Waiting for other member to comment...

**Comment by aykol** [comment] 2016-12-15 07:01
@albalu I also experienced this issue.

**Comment by albalu** [comment] 2016-12-15 07:12
@aykol it's good to know that I'm not the only one. Do you have the error message by any chance? Is it the one I posted at the beginning? 

The problem with the solution I proposed is that those files may already exist.

**Comment by aykol** [comment] 2016-12-15 07:56
I have experienced this multiple times. The one I could find right now is also an error at the slurm end:
`slurmstepd: error: execve(): vasp_std: No such file or directory`
As you said, if VASP doesn't even start for some reason (I guess here the module was not available temporarily)

**Comment by aykol** [comment] 2016-12-15 08:18
@albalu I suggest a solution based on timestamps of creation of custodian.json and vasprun.xml:
`os.path.getmtime("vasprun.xml") - os.path.getctime("custodian.json")`
This should return a negative number if vasp failed to start.

**Comment by computron** [comment] 2016-12-15 16:55
@albalu @aykol @xhqu1981 

All - this thread is getting ridiculous.

Here is our problem, simply stated:

We have a Firework with 4 Firetasks:
- copy output from a previous run (OUTCAR and vasprun.xml)
- use that information to generate inputs (INCAR, POSCAR, KPOINTS, POTCAR) for the current run
- use custodian to run VASP
- parse the resulting output files and put them in the database

What we have found is that, in many instances, this Firework looks to be COMPLETED successfully. It is listed as COMPLETED in the Fireworks database, and in the tasks database there is indeed a new entry (meaning all 4 Firetasks did in fact complete). So far, nothing appears to be the problem.

But, upon closer inspection of the directory, what has actually happened is that step 3 (use custodian to run VASP) never actually executed correctly. During this part, when calling the mpirun command, there was some error returned from NERSC/SLURM/whatever and thus vasp never actually started. This is almost certainly due to some temporary issue that happened at NERSC. Unfortunately, because step 3 never throws an error in such cases, step 4 continues as normal - parsing the outputs (which are actually copied from the previous run, i.e., from step 1) and inserting those previous outputs in the database. The resulting database entry is for the previous run, and uses all the parameters/outputs of the previous run. Furthermore, downstream Fireworks still run in this instance (since the current Firework is COMPLETED) but then fail.

Ideally, we would like for the chain of execution to stop as soon as there is a failure, i.e., when the mpirun command cannot complete successfully. This will prevent problems like incorrect database entries being inserted as well as downstream Fireworks running. *We would like for custodian to check the returncode from the run, and if it is not zero, to throw an error (or at least have an option to enable this).* If this were implemented, the errors would be extremely easy to debug and fix. As it stands, with bad database entries and downstream Fireworks failing for strange reasons, this is not the case.

Alireza and I have also talked about alternate solutions that don't involve custodian - e.g., such as deleting the output files of the old run from the current directory once we are done using them to generate input files. We have also discussed other validation enhancements such as having the MatMethods Vaspdrone check for more output files (e.g., EIGENVAL, IBZKPT) rather than just the OUTCAR/vasprun.xml - this would also solve our specific problem. But the best solution is if custodian throws an error when executing a job shell command and getting a non-zero error code.

**Comment by computron** [comment] 2016-12-15 17:04
Btw, I hope the above makes it clear that @xhqu1981 's theory on the problem is likely not the one that we are experiencing. My guess is that step 3 (running vasp custodian) fails almost immediately. @albalu could easily double check this by checking the timestamps on the launch object, which will most likely show that the time between running the Firework and completing the entire Firework is small.

Also the timestamp solution suggested by @aykol is possibly another type of validation that we can add, although I worry this could be kind of finicky. Again, @shyuep  - ideally the best solution is if custodian can check the returncode of scripts that it runs and raise an error if there is a non-zero error code. The ScriptTask that is built into FireWorks does this, for example. i.e., extract a small portion of the code below to see that FireWorks is grabbing the returncode from the process (```p.returncode```), and if all the returncodes from all the scripts are not zero, to defuse or fizzle the Firework if the user sets this option.

```
       returncodes = []
        for s in self.script:
            p = subprocess.Popen(
                s, executable=self.shell_exe, stdin=stdin,
                stdout=stdout, stderr=stderr,
                shell=self.use_shell)

            # communicate in the standard in and get back the standard out and returncode
            if self.stdin_key:
                (stdout, stderr) = p.communicate(fw_spec[self.stdin_key])
            else:
                (stdout, stderr) = p.communicate()
            returncodes.append(p.returncode)

            #Stop execution if any script command fails.
            if p.returncode != 0:
                break

        # write out the output, error files if specified

        stdout = stdout.decode('utf-8') if isinstance(stdout, bytes) else stdout
        stderr = stderr.decode('utf-8') if isinstance(stderr, bytes) else stderr

        if self.stdout_file:
            with open(self.stdout_file, 'a+') as f:
                f.write(stdout)

        if self.stderr_file:
            with open(self.stderr_file, 'a+') as f:
                f.write(stderr)

        # write the output keys
        output = {}

        if self.store_stdout:
            output['stdout'] = stdout

        if self.store_stderr:
            output['stderr'] = stderr

        output['returncode'] = returncodes[-1]
        output['all_returncodes'] = returncodes

        if self.defuse_bad_rc and sum(returncodes) != 0:
            return FWAction(stored_data=output, defuse_children=True)

        elif self.fizzle_bad_rc and sum(returncodes) != 0:
            raise RuntimeError('ScriptTask fizzled! Return code: {}'.format(returncodes))
```

**Comment by xhqu1981** [comment] 2016-12-15 17:38
As a @albalu has said, the file "vasp.out" is empty, @shyuep @computron @aykol I think the custodian should have a mechanism to look for graceful termination message in "vasp.out". It would an elegant way to solve the issue @albalu experienced and doesn't need to involve timestamp. Also, easier to implement.

BTW, I have confirmed that it is not a VASP stuck case about 12 hours ago after @albalu is 100% sure that the running time is less than 5 min.

**Comment by albalu** [comment] 2016-12-15 17:44
I just checked and the time between start and completion of RunVaspCustodian jobs is 80-100 seconds and as I said none of the files that are normally generated immediately after running of VASP are generated (e.g. EIGENVAL, CONTCAR, OSZCAR)

"
961-2016-12-02 18:29:20,165 INFO Task started: {{matmethods.vasp.firetasks.run_calc.RunVaspCustodian}}.
962-2016-12-02 18:30:40,858 INFO Task completed: {{matmethods.vasp.firetasks.run_calc.RunVaspCustodian}} 
"

**Comment by shyamd** [comment] 2016-12-15 17:52
Should be taken care of with #38 which checks for return code and throws an error. Also added a test for this in #39.

**Comment by computron** [comment] 2016-12-15 18:01
@shyamd Thanks! I am going to close this issue on Alireza's behalf and he can reopen it if there are still problems.

**Closed by computron** 2016-12-15 18:01 UTC
