### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by miaoliu** [materialsproject/custodian#13] opened 2015-09-08 20:49 UTC
unable to install it on nersc

Got error like this.

$ python setup.py develop 
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    long_desc = f.read()
  File "/global/u1/m/mliu/ml_web/virtenv_ml_web/lib/python2.7/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3323: ordinal not in range(128)

**Comment by computron** [comment] 2015-09-10 04:53
This was caused by a unicode dash character in the README (either em or en dash instead of hyphen), which is used in the long_description of setup.py. I pushed a fix

**Closed by computron** 2015-09-10 04:53 UTC
